language: node_js
node_js:
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "iojs"
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
sudo: false
