language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "iojs"
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
